services:
  vite-app:
    build: .
    container_name: vite-swc-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
